# Use phusion/baseimage as base image. 
FROM phusion/baseimage:0.9.19
MAINTAINER evansde77.github@gmail.com

# Use baseimage-docker's init system.
CMD ["/sbin/my_init"]

#
# install apt packages and deps
#
# if we want to add docker and do DinD we need this 
#RUN apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
#RUN echo "deb https://apt.dockerproject.org/repo ubuntu-xenial main" | tee /etc/apt/sources.list.d/docker.list

RUN apt-get update && apt-cache policy docker-engine && apt-get -y install {{#apt_packages}} {{.}} {{/apt_packages}}

WORKDIR /opt/{{user}}
RUN mkdir -p /opt/{{user}}/logs
RUN groupadd {{group}}
RUN useradd -m -g {{group}} {{user}}
RUN chown -R {{user}}:{{group}} /opt/{{user}}

ENV HOME  /opt/{{user}}
ENV PYENV_ROOT $HOME/.pyenv
ENV PATH $PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH

ADD pyenv_setup.sh /opt/{{user}}/pyenv_setup.sh
RUN . /opt/{{user}}/pyenv_setup.sh
ADD venv_setup.sh /opt/{{user}}/venv_setup.sh
RUN . /opt/{{user}}/venv_setup.sh

# Clean up APT when done.
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*